### ISSUE TITLE
Are you kidding me?

### ISSUE THREAD

**Issue by f0rem4n** [ItsIgnacioPortal/mass-reddit-downvoter#2]
Spez, gallowboob, and me? 

I appreciate the notoriety lmao

**Comment by ItsIgnacioPortal** [comment]
lmao

I only put them there bc for some reason those accounts are the default on [the project this was inspired by](https://github.com/mike-duran-mitchell/connect-to-reddit-api) (see: index.js line 11)

I can remove them if u want

**Comment by f0rem4n** [comment]
no worries, I only stumbled on this doing a web security check. I'm nowhere near the other two accounts in terms of stature, so I must have upset someone back in then day. It was really weird to discover. Appreciate the response.

**Comment by ItsIgnacioPortal** [comment]
> web security check

You looked up your username and this repository popped up? How'd you find this?
