### ISSUE TITLE
bad request (reddit.com)

### ISSUE THREAD

**Issue by wildfirebill** [ItsIgnacioPortal/mass-reddit-downvoter#3]
bad request (reddit.com)

you sent an invalid request
— invalid redirect_uri parameter.

I have rechecked, recreated, cleared cache, nothing seems to get past bad request

**Comment by ItsIgnacioPortal** [comment]
Where does this error pop-up? in the terminal, or in the browser?
I'll be closing this issue, but I'll reopen it if you answer

**Comment by Odyssey28** [comment]
I got this error using a browser, am I not supposed to use a browser? BTW, why would only comments from the last month be downvoted?

You should make the guide easier for us idiots...
