### ISSUE TITLE
is this still working???

### ISSUE THREAD

**Issue by eawlot3000** [ItsIgnacioPortal/mass-reddit-downvoter#4]
i try exact every steps you did, its a bad request on reddit.
what i got:
```
you sent an invalid request
— invalid redirect_uri parameter.
```
why???

**Comment by ItsIgnacioPortal** [comment]
The fix is to https://www.reddit.com/prefs/apps and remove `#usage` from the redirect URI. So, the redirect uri should be `https://github.com/ItsIgnacioPortal/mass-reddit-downvoter`. Then open your modified link
